/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CalcRecord {
  'id' : bigint,
  'item' : string,
  'difference' : number,
  'investment' : number,
  'sector' : string,
  'sales' : number,
  'timestamp' : bigint,
  'resultType' : string,
}
export interface ManualPaymentRecord {
  'method' : string,
  'principal' : Principal,
  'verified' : boolean,
  'timestamp' : bigint,
  'transactionId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscriber {
  'status' : SubscriptionStatus,
  'principal' : Principal,
}
export type SubscriptionStatus = { 'active' : null } |
  { 'inactive' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'language' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface YearlySummary {
  'totalInvestment' : number,
  'totalLoss' : number,
  'totalProfit' : number,
  'totalSales' : number,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Feedback {
  'id' : bigint,
  'principal' : Principal,
  'name' : string,
  'rating' : bigint,
  'text' : string,
  'timestamp' : bigint,
  'approved' : boolean,
}
export interface Complaint {
  'id' : bigint,
  'principal' : Principal,
  'name' : string,
  'text' : string,
  'timestamp' : bigint,
  'status' : string,
}
export interface GovPriceEntry {
  'sector' : string,
  'item' : string,
  'price' : number,
  'unit' : string,
  'qty' : number,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'accessCalculator' : ActorMethod<[string], boolean>,
  'activateSubscription' : ActorMethod<[Principal, string], boolean>,
  'approveFeedback' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCropYield' : ActorMethod<[number, string], number>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deactivateSubscription' : ActorMethod<[Principal], undefined>,
  'deleteCalcRecord' : ActorMethod<[bigint], undefined>,
  'deleteFeedback' : ActorMethod<[bigint], undefined>,
  'getAllFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'getAllSubscribers' : ActorMethod<[], Array<Subscriber>>,
  'getApprovedFeedbacks' : ActorMethod<[], Array<Feedback>>,
  'getCalcHistory' : ActorMethod<[], Array<CalcRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComplaints' : ActorMethod<[], Array<Complaint>>,
  'getGovPrices' : ActorMethod<[], Array<GovPriceEntry>>,
  'getManualPayments' : ActorMethod<[], Array<ManualPaymentRecord>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getYearlySummary' : ActorMethod<[], YearlySummary>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerSubscribed' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCalcRecord' : ActorMethod<
    [string, string, number, number, number, string],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAllGovPrices' : ActorMethod<[Array<GovPriceEntry>], undefined>,
  'setGovPrice' : ActorMethod<[string, string, number, string, number], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitComplaint' : ActorMethod<[string, string], bigint>,
  'submitFeedback' : ActorMethod<[string, bigint, string], bigint>,
  'submitManualPayment' : ActorMethod<[string, string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateComplaintStatus' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
