/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Subscriber = IDL.Record({
  'status' : SubscriptionStatus,
  'principal' : IDL.Principal,
});
export const CalcRecord = IDL.Record({
  'id' : IDL.Nat,
  'item' : IDL.Text,
  'difference' : IDL.Float64,
  'investment' : IDL.Float64,
  'sector' : IDL.Text,
  'sales' : IDL.Float64,
  'timestamp' : IDL.Int,
  'resultType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'language' : IDL.Text,
});
export const ManualPaymentRecord = IDL.Record({
  'method' : IDL.Text,
  'principal' : IDL.Principal,
  'verified' : IDL.Bool,
  'timestamp' : IDL.Int,
  'transactionId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const YearlySummary = IDL.Record({
  'totalInvestment' : IDL.Float64,
  'totalLoss' : IDL.Float64,
  'totalProfit' : IDL.Float64,
  'totalSales' : IDL.Float64,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'accessCalculator' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'activateSubscription' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCropYield' : IDL.Func(
      [IDL.Float64, IDL.Text],
      [IDL.Float64],
      ['query'],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deactivateSubscription' : IDL.Func([IDL.Principal], [], []),
  'deleteCalcRecord' : IDL.Func([IDL.Nat], [], []),
  'getAllSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'getCalcHistory' : IDL.Func([], [IDL.Vec(CalcRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getManualPayments' : IDL.Func([], [IDL.Vec(ManualPaymentRecord)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getYearlySummary' : IDL.Func([], [YearlySummary], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCalcRecord' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitManualPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Subscriber = IDL.Record({
    'status' : SubscriptionStatus,
    'principal' : IDL.Principal,
  });
  const CalcRecord = IDL.Record({
    'id' : IDL.Nat,
    'item' : IDL.Text,
    'difference' : IDL.Float64,
    'investment' : IDL.Float64,
    'sector' : IDL.Text,
    'sales' : IDL.Float64,
    'timestamp' : IDL.Int,
    'resultType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'language' : IDL.Text });
  const ManualPaymentRecord = IDL.Record({
    'method' : IDL.Text,
    'principal' : IDL.Principal,
    'verified' : IDL.Bool,
    'timestamp' : IDL.Int,
    'transactionId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const YearlySummary = IDL.Record({
    'totalInvestment' : IDL.Float64,
    'totalLoss' : IDL.Float64,
    'totalProfit' : IDL.Float64,
    'totalSales' : IDL.Float64,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'accessCalculator' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'activateSubscription' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCropYield' : IDL.Func(
        [IDL.Float64, IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deactivateSubscription' : IDL.Func([IDL.Principal], [], []),
    'deleteCalcRecord' : IDL.Func([IDL.Nat], [], []),
    'getAllSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'getCalcHistory' : IDL.Func([], [IDL.Vec(CalcRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getManualPayments' : IDL.Func(
        [],
        [IDL.Vec(ManualPaymentRecord)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getYearlySummary' : IDL.Func([], [YearlySummary], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerSubscribed' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCalcRecord' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitManualPayment' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };